server:
  port: 8082
  servlet:
    context-path: /
spring:
  rabbitmq:
    host: 192.168.120.128
    port: 5672
    virtual-host: /
    listener:
      simple:
        # 表示消费者，消费成功消息后，需要手工签收（ack），默认为auto
        # auto:自动确认消息，manual:手动确认消息,none:不确认
        acknowledge-mode: manual