server:
  port: 8081
  servlet:
    context-path: /
spring:
  application:
    name: rabbit-producer
  rabbitmq:
    addresses: 192.168.120.128
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 启用消息确认模式
    publisher-confirms: true
#    // 设置return消息模式，注意要和man
#    publisher-returns: true
#    template:
#      mandatory: true
    # 超时时间
    connection-timeout: 15000
  http:
    encoding:
      charset: utf-8
  jackson:
    date-format: java.text.SimpleDateFormat
    default-property-inclusion: non_null
    time-zone: GMT+8